# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /root/DOWNLOAD/U50/U50-PCIE/u50_pcie_xdma/pcie_xdma_test.srcs/sources_1/ip/fp32_add_0/fp32_add_0.xci
# IP: The module: 'fp32_add_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /root/DOWNLOAD/U50/U50-PCIE/u50_pcie_xdma/pcie_xdma_test.gen/sources_1/ip/fp32_add_0/fp32_add_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp32_add_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /root/DOWNLOAD/U50/U50-PCIE/u50_pcie_xdma/pcie_xdma_test.srcs/sources_1/ip/fp32_add_0/fp32_add_0.xci
# IP: The module: 'fp32_add_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /root/DOWNLOAD/U50/U50-PCIE/u50_pcie_xdma/pcie_xdma_test.gen/sources_1/ip/fp32_add_0/fp32_add_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fp32_add_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
